export { default as Login } from './auth/Login'
export { default as Register } from './auth/Register'
export { default as ForgotPassword } from './auth/ForgotPassword'
export { default as ResetPassword } from './auth/ResetPassword'
export { default as BusinessUpgrade } from './upgrades/BusinessUpgrade'
export { default as TalentUpgrade } from './upgrades/TalentUpgrade'
export { default as TalentGetStarted } from './upgrades/TalentGetStarted'
export { default as BusinessGetStarted } from './upgrades/BusinessGetStarted'
export { default as TalentOnboarding } from './upgrades/TalentOnboarding'
export { default as BusinessOnboarding } from './upgrades/BusinessOnboarding'
export { default as Home } from './Home'
// export { default as DashboardEvents } from './dashboard/Events'
// export { default as DashboardCreateEvent } from './dashboard/CreateEvent'
// export { default as DashboardContacts } from './dashboard/Contacts'
// export { default as DashboardCreateContact } from './dashboard/CreateContact'